/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mycamera_Computation */

#ifndef _Included_com_example_mycamera_Computation
#define _Included_com_example_mycamera_Computation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mycamera_Computation
 * Method:    Compute
 * Signature: (JJ)J
 */
JNIEXPORT void JNICALL Java_com_example_mycamera_Computation_Compute
  (JNIEnv *, jclass, jlong,jfloatArray,jfloatArray,jintArray);

#ifdef __cplusplus
}
#endif
#endif
